- params:
         git:
           repoName: springbootexample
           branches:
             - master
         scan:
           packageManager: mvn
           installDepsCmd: mvn install
           includeAllVulnerabilities: true